// -*- C++ -*- generated by wxGlade 0.5 on Fri Jun 15 22:36:02 2007 from C:\Documents and Settings\koji\My Documents\saved_\repository_\marathon\MapEditorWX\src\res\MapEditorWX.wxg

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
#include <wx/listctrl.h>
// end wxGlade


#ifndef DIALOGUES_H
#define DIALOGUES_H


class wxDialog: public wxDialog {
public:
    // begin wxGlade: wxDialog::ids
    // end wxGlade

    wxDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: wxDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxDialog::attributes
    wxStaticBox* sizer_31_staticbox;
    wxStaticBox* sizer_27_staticbox;
    wxStaticBox* sizer_28_staticbox;
    wxStaticBox* sizer_19_staticbox;
    wxStaticBox* sizer_12_staticbox;
    wxStaticBox* sizer_11_staticbox;
    wxStaticBox* sizer_10_staticbox;
    wxStaticText* label_1;
    wxChoice* choice_1;
    wxStaticText* label_2;
    wxTextCtrl* text_ctrl_1;
    wxChoice* choice_2;
    wxStaticText* label_3;
    wxTextCtrl* text_ctrl_2;
    wxChoice* choice_3;
    wxCheckBox* checkbox_7;
    wxStaticText* label_4;
    wxTextCtrl* text_ctrl_3;
    wxCheckBox* checkbox_8;
    wxStaticText* label_5;
    wxTextCtrl* text_ctrl_4;
    wxCheckBox* checkbox_1;
    wxCheckBox* checkbox_2;
    wxCheckBox* checkbox_3;
    wxCheckBox* checkbox_4;
    wxCheckBox* checkbox_5;
    wxCheckBox* checkbox_6;
    wxCheckBox* checkbox_9;
    wxStaticText* label_6;
    wxChoice* choice_4;
    wxRadioButton* radio_btn_1;
    wxRadioButton* radio_btn_2;
    wxRadioButton* radio_btn_3;
    wxCheckBox* checkbox_10;
    wxStaticText* label_7;
    wxChoice* choice_5;
    wxCheckBox* checkbox_15;
    wxCheckBox* checkbox_16;
    wxCheckBox* checkbox_17;
    wxCheckBox* checkbox_18;
    wxCheckBox* checkbox_19;
    wxStaticText* label_8;
    wxChoice* choice_6;
    wxRadioButton* radio_btn_4;
    wxRadioButton* radio_btn_5;
    wxRadioButton* radio_btn_6;
    wxCheckBox* checkbox_12;
    wxCheckBox* checkbox_13;
    wxCheckBox* checkbox_14;
    wxCheckBox* checkbox_20;
    wxCheckBox* checkbox_21;
    wxCheckBox* checkbox_22;
    wxCheckBox* checkbox_24;
    wxCheckBox* checkbox_23;
    wxCheckBox* checkbox_25;
    wxCheckBox* checkbox_26;
    wxButton* button_1;
    wxButton* button_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnChoiceType(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class HeightDialog1: public wxDialog {
public:
    // begin wxGlade: HeightDialog1::ids
    // end wxGlade

    HeightDialog1(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: HeightDialog1::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HeightDialog1::attributes
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_5;
    wxSlider* slider_2;
    wxSlider* slider_3;
    wxStaticText* label_10;
    wxTextCtrl* text_ctrl_6;
    wxCheckBox* checkbox_11;
    // end wxGlade
}; // wxGlade: end class


class AnnotationDialog: public wxDialog {
public:
    // begin wxGlade: AnnotationDialog::ids
    // end wxGlade

    AnnotationDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: AnnotationDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AnnotationDialog::attributes
    wxStaticText* label_12;
    wxChoice* choice_8;
    wxTextCtrl* text_ctrl_7;
    wxStaticText* label_11;
    wxChoice* choice_7;
    wxButton* button_3;
    wxButton* button_4;
    // end wxGlade
}; // wxGlade: end class


class ColorCustomize: public wxDialog {
public:
    // begin wxGlade: ColorCustomize::ids
    // end wxGlade

    ColorCustomize(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ColorCustomize::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ColorCustomize::attributes
    wxStaticText* label_13;
    wxButton* button_7;
    wxPanel* panel_1;
    wxStaticText* label_14;
    wxButton* button_8;
    wxPanel* panel_2;
    wxStaticText* label_16;
    wxButton* button_9;
    wxPanel* panel_3;
    wxStaticText* label_15;
    wxButton* button_10;
    wxPanel* panel_4;
    wxStaticText* label_17;
    wxButton* button_11;
    wxPanel* panel_5;
    wxStaticText* label_18;
    wxButton* button_12;
    wxPanel* panel_6;
    wxButton* button_5;
    wxButton* button_6;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnBackground(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnGrid(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnLines(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnPolygons(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnStrings(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnPoints(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOk(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnCancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class EditorPreferences: public wxDialog {
public:
    // begin wxGlade: EditorPreferences::ids
    // end wxGlade

    EditorPreferences(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: EditorPreferences::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditorPreferences::attributes
    wxStaticText* label_19;
    wxChoice* choice_9;
    wxCheckBox* checkbox_27;
    wxCheckBox* checkbox_28;
    wxCheckBox* checkbox_31;
    wxCheckBox* checkbox_30;
    wxCheckBox* checkbox_32;
    wxCheckBox* checkbox_33;
    wxCheckBox* checkbox_34;
    wxCheckBox* checkbox_35;
    wxCheckBox* checkbox_36;
    wxCheckBox* checkbox_29;
    wxStaticText* label_20;
    wxChoice* choice_10;
    wxCheckBox* checkbox_37;
    wxCheckBox* checkbox_38;
    wxButton* button_15;
    wxButton* button_13;
    wxButton* button_14;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnDefault(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOk(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnCancel(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class PlacementDialog: public wxDialog {
public:
    // begin wxGlade: PlacementDialog::ids
    // end wxGlade

    PlacementDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: PlacementDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PlacementDialog::attributes
    wxStaticText* label_21;
    wxTextCtrl* text_ctrl_8;
    wxStaticText* label_22;
    wxTextCtrl* text_ctrl_9;
    wxStaticText* label_23;
    wxTextCtrl* text_ctrl_10;
    wxStaticText* label_24;
    wxTextCtrl* text_ctrl_11;
    wxStaticText* label_25;
    wxTextCtrl* text_ctrl_12;
    wxButton* button_17;
    wxButton* button_18;
    wxButton* button_19;
    wxCheckBox* checkbox_39;
    wxListCtrl* list_ctrl_1;
    wxButton* button_16;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnEditInitial(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditMinimum(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditMaximum(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditRandomCount(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnRandomChance(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOk(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class TerminalDialog: public wxDialog {
public:
    // begin wxGlade: TerminalDialog::ids
    // end wxGlade

    TerminalDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: TerminalDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: TerminalDialog::attributes
    wxListBox* list_box_1;
    wxListBox* list_box_2;
    wxListBox* list_box_3;
    wxPanel* panel_7;
    wxTextCtrl* text_ctrl_13;
    wxButton* button_20;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnSelTerminal(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSelScreen(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSelInfo(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEdit(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnOk(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class PointPropDialog: public wxDialog {
public:
    // begin wxGlade: PointPropDialog::ids
    // end wxGlade

    PointPropDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: PointPropDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PointPropDialog::attributes
    wxStaticBox* sizer_52_staticbox;
    wxRadioButton* radio_btn_7;
    wxRadioButton* radio_btn_8;
    wxCheckBox* checkbox_40;
    wxStaticText* label_29;
    wxTextCtrl* text_ctrl_14;
    wxPanel* panel_8;
    wxStaticText* label_30;
    wxTextCtrl* text_ctrl_15;
    wxPanel* panel_9;
    wxStaticText* label_31;
    wxTextCtrl* text_ctrl_16;
    wxTextCtrl* text_ctrl_18;
    wxStaticText* label_32;
    wxTextCtrl* text_ctrl_17;
    wxTextCtrl* text_ctrl_19;
    wxStaticText* label_33;
    wxChoice* choice_11;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnEditFloor(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditCeiling(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEdit(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditY(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditTX(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnEditTY(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnPolyChoice(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class PolygonPropDialog: public wxDialog {
public:
    // begin wxGlade: PolygonPropDialog::ids
    // end wxGlade

    PolygonPropDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: PolygonPropDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PolygonPropDialog::attributes
    wxStaticText* label_34;
    wxStaticText* label_46;
    wxStaticText* label_35;
    wxStaticText* label_47;
    wxStaticText* label_36;
    wxStaticText* label_48;
    wxStaticText* label_37;
    wxStaticText* label_49;
    wxStaticText* label_38;
    wxStaticText* label_39;
    wxStaticText* label_55;
    wxStaticText* label_40;
    wxStaticText* label_54;
    wxStaticText* label_41;
    wxStaticText* label_53;
    wxStaticText* label_42;
    wxStaticText* label_52;
    wxStaticText* label_43;
    wxStaticText* label_51;
    wxStaticText* label_44;
    wxStaticText* label_50;
    wxStaticText* label_45;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGUES_H
