// -*- C++ -*- generated by wxGlade 0.5 on Fri Jun 15 14:25:30 2007 from C:\0save\marathon\MapEditorWX\src\res\MapEditorWX.wxg

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef DIALOGUES_H
#define DIALOGUES_H


class wxDialog: public wxDialog {
public:
    // begin wxGlade: wxDialog::ids
    // end wxGlade

    wxDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: wxDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxDialog::attributes
    wxStaticBox* sizer_31_staticbox;
    wxStaticBox* sizer_27_staticbox;
    wxStaticBox* sizer_28_staticbox;
    wxStaticBox* sizer_19_staticbox;
    wxStaticBox* sizer_12_staticbox;
    wxStaticBox* sizer_11_staticbox;
    wxStaticBox* sizer_10_staticbox;
    wxStaticText* label_1;
    wxChoice* choice_1;
    wxStaticText* label_2;
    wxTextCtrl* text_ctrl_1;
    wxChoice* choice_2;
    wxStaticText* label_3;
    wxTextCtrl* text_ctrl_2;
    wxChoice* choice_3;
    wxCheckBox* checkbox_7;
    wxStaticText* label_4;
    wxTextCtrl* text_ctrl_3;
    wxCheckBox* checkbox_8;
    wxStaticText* label_5;
    wxTextCtrl* text_ctrl_4;
    wxCheckBox* checkbox_1;
    wxCheckBox* checkbox_2;
    wxCheckBox* checkbox_3;
    wxCheckBox* checkbox_4;
    wxCheckBox* checkbox_5;
    wxCheckBox* checkbox_6;
    wxCheckBox* checkbox_9;
    wxStaticText* label_6;
    wxChoice* choice_4;
    wxRadioButton* radio_btn_1;
    wxRadioButton* radio_btn_2;
    wxRadioButton* radio_btn_3;
    wxCheckBox* checkbox_10;
    wxStaticText* label_7;
    wxChoice* choice_5;
    wxCheckBox* checkbox_15;
    wxCheckBox* checkbox_16;
    wxCheckBox* checkbox_17;
    wxCheckBox* checkbox_18;
    wxCheckBox* checkbox_19;
    wxStaticText* label_8;
    wxChoice* choice_6;
    wxRadioButton* radio_btn_4;
    wxRadioButton* radio_btn_5;
    wxRadioButton* radio_btn_6;
    wxCheckBox* checkbox_12;
    wxCheckBox* checkbox_13;
    wxCheckBox* checkbox_14;
    wxCheckBox* checkbox_20;
    wxCheckBox* checkbox_21;
    wxCheckBox* checkbox_22;
    wxCheckBox* checkbox_24;
    wxCheckBox* checkbox_23;
    wxCheckBox* checkbox_25;
    wxCheckBox* checkbox_26;
    wxButton* button_1;
    wxButton* button_2;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnChoiceType(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class HeightDialog1: public wxDialog {
public:
    // begin wxGlade: HeightDialog1::ids
    // end wxGlade

    HeightDialog1(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: HeightDialog1::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HeightDialog1::attributes
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_5;
    wxSlider* slider_2;
    wxSlider* slider_3;
    wxStaticText* label_10;
    wxTextCtrl* text_ctrl_6;
    wxCheckBox* checkbox_11;
    // end wxGlade
}; // wxGlade: end class


class AnnotationDialog: public wxDialog {
public:
    // begin wxGlade: AnnotationDialog::ids
    // end wxGlade

    AnnotationDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: AnnotationDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: AnnotationDialog::attributes
    wxStaticText* label_12;
    wxChoice* choice_8;
    wxTextCtrl* text_ctrl_7;
    wxStaticText* label_11;
    wxChoice* choice_7;
    wxButton* button_3;
    wxButton* button_4;
    // end wxGlade
}; // wxGlade: end class


class ColorCustomize: public wxDialog {
public:
    // begin wxGlade: ColorCustomize::ids
    // end wxGlade

    ColorCustomize(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: ColorCustomize::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: ColorCustomize::attributes
    wxStaticText* label_13;
    wxButton* button_7;
    wxPanel* panel_1;
    wxStaticText* label_14;
    wxButton* button_8;
    wxPanel* panel_2;
    wxStaticText* label_16;
    wxButton* button_9;
    wxPanel* panel_3;
    wxStaticText* label_15;
    wxButton* button_10;
    wxPanel* panel_4;
    wxStaticText* label_17;
    wxButton* button_11;
    wxPanel* panel_5;
    wxStaticText* label_18;
    wxButton* button_12;
    wxPanel* panel_6;
    wxButton* button_5;
    wxButton* button_6;
    // end wxGlade
}; // wxGlade: end class


class EditorPreferences: public wxDialog {
public:
    // begin wxGlade: EditorPreferences::ids
    // end wxGlade

    EditorPreferences(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: EditorPreferences::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: EditorPreferences::attributes
    wxStaticText* label_19;
    wxChoice* choice_9;
    wxCheckBox* checkbox_27;
    wxCheckBox* checkbox_28;
    wxCheckBox* checkbox_31;
    wxCheckBox* checkbox_30;
    wxCheckBox* checkbox_32;
    wxCheckBox* checkbox_33;
    wxCheckBox* checkbox_34;
    wxCheckBox* checkbox_35;
    wxCheckBox* checkbox_36;
    wxCheckBox* checkbox_29;
    wxStaticText* label_20;
    wxChoice* choice_10;
    wxCheckBox* checkbox_37;
    wxCheckBox* checkbox_38;
    wxButton* button_15;
    wxButton* button_13;
    wxButton* button_14;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGUES_H
