// -*- C++ -*- generated by wxGlade 0.5 on Wed Jun 13 16:40:26 2007 from C:\0save\marathon\MapEditorWX\src\res\MapEditorWX.wxg

#include <wx/wx.h>
#include <wx/image.h>
// begin wxGlade: ::dependencies
// end wxGlade


#ifndef DIALOGUES_H
#define DIALOGUES_H


class wxDialog: public wxDialog {
public:
    // begin wxGlade: wxDialog::ids
    // end wxGlade

    wxDialog(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: wxDialog::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: wxDialog::attributes
    wxStaticBox* sizer_19_staticbox;
    wxStaticBox* sizer_12_staticbox;
    wxStaticBox* sizer_11_staticbox;
    wxStaticBox* sizer_10_staticbox;
    wxStaticText* label_1;
    wxChoice* choice_1;
    wxStaticText* label_2;
    wxTextCtrl* text_ctrl_1;
    wxChoice* choice_2;
    wxStaticText* label_3;
    wxTextCtrl* text_ctrl_2;
    wxChoice* choice_3;
    wxCheckBox* checkbox_7;
    wxStaticText* label_4;
    wxTextCtrl* text_ctrl_3;
    wxCheckBox* checkbox_8;
    wxStaticText* label_5;
    wxTextCtrl* text_ctrl_4;
    wxCheckBox* checkbox_1;
    wxCheckBox* checkbox_2;
    wxCheckBox* checkbox_3;
    wxCheckBox* checkbox_4;
    wxCheckBox* checkbox_5;
    wxCheckBox* checkbox_6;
    wxCheckBox* checkbox_9;
    wxStaticText* label_6;
    wxChoice* choice_4;
    wxRadioButton* radio_btn_1;
    wxRadioButton* radio_btn_2;
    wxRadioButton* radio_btn_3;
    wxCheckBox* checkbox_10;
    wxStaticText* label_7;
    wxChoice* choice_5;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnChoiceType(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


class HeightDialog1: public wxDialog {
public:
    // begin wxGlade: HeightDialog1::ids
    // end wxGlade

    HeightDialog1(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_DIALOG_STYLE);

private:
    // begin wxGlade: HeightDialog1::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: HeightDialog1::attributes
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_5;
    wxSlider* slider_2;
    wxSlider* slider_3;
    wxStaticText* label_10;
    wxTextCtrl* text_ctrl_6;
    wxCheckBox* checkbox_11;
    // end wxGlade
}; // wxGlade: end class


#endif // DIALOGUES_H
