// -*- C++ -*- generated by wxGlade 0.5 on Mon Aug 13 13:06:37 2007 from C:\0save\marathon\EditorOnes\PhysicsEditorOneWX\src\res\PhysicsEditorOneWX.wxg

#include <wx/wx.h>
#include <wx/image.h>

#ifndef PHYSICSEDITORMAINFRAME_H
#define PHYSICSEDITORMAINFRAME_H

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


class PhysicsEditorMainFrame: public wxFrame {
public:
    // begin wxGlade: PhysicsEditorMainFrame::ids
    // end wxGlade

    PhysicsEditorMainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: PhysicsEditorMainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PhysicsEditorMainFrame::attributes
    wxStaticBox* sizer_8_staticbox;
    wxStaticBox* sizer_7_staticbox;
    wxStaticBox* sizer_6_staticbox;
    wxStaticBox* sizer_5_staticbox;
    wxStaticBox* sizer_4_staticbox;
    wxStaticBox* sizer_3_staticbox;
    wxStaticBox* sizer_2_staticbox;
    wxMenuBar* frame_1_menubar;
    wxListBox* list_box_1;
    wxStaticText* label_2;
    wxChoice* choice_col;
    wxStaticText* label_3;
    wxTextCtrl* text_ctrl_pal;
    wxStaticText* label_4;
    wxTextCtrl* text_ctrl_vi;
    wxStaticText* label_5;
    wxChoice* choice_cls;
    wxStaticText* label_6;
    wxTextCtrl* text_ctrl_r;
    wxStaticText* label_7;
    wxTextCtrl* text_ctrl_h;
    wxStaticText* label_8;
    wxTextCtrl* text_ctrl_hov;
    wxStaticText* label_9;
    wxTextCtrl* text_ctrl_minLedge;
    wxStaticText* label_10;
    wxTextCtrl* text_ctrl_maxLedge;
    wxStaticText* label_11;
    wxTextCtrl* text_ctrl_ext;
    wxStaticText* label_12;
    wxChoice* choice_item;
    wxStaticText* label_13;
    wxTextCtrl* text_ctrl_hVisArc;
    wxStaticText* label_14;
    wxTextCtrl* text_ctrl_vVisArc;
    wxStaticText* label_15;
    wxChoice* choice_intelligence;
    wxStaticText* label_16;
    wxTextCtrl* text_ctrl_spd;
    wxStaticText* label_18;
    wxChoice* choice_spdPreset;
    wxStaticText* label_17;
    wxTextCtrl* text_ctrl_g;
    wxStaticText* label_19;
    wxTextCtrl* text_ctrl_13;
    wxStaticText* label_21;
    wxTextCtrl* text_ctrl_14;
    wxStaticText* label_22;
    wxTextCtrl* text_ctrl_15;
    wxStaticText* label_23;
    wxTextCtrl* text_ctrl_16;
    wxStaticText* label_24;
    wxTextCtrl* text_ctrl_17;
    wxStaticText* label_25;
    wxTextCtrl* text_ctrl_18;
    wxStaticText* label_26;
    wxTextCtrl* text_ctrl_19;
    wxStaticText* label_27;
    wxTextCtrl* text_ctrl_20;
    wxStaticText* label_20;
    wxTextCtrl* text_ctrl_21;
    wxStaticText* label_28;
    wxTextCtrl* text_ctrl_22;
    wxStaticText* label_29;
    wxTextCtrl* text_ctrl_23;
    wxStaticText* label_30;
    wxTextCtrl* text_ctrl_24;
    wxStaticText* label_31;
    wxTextCtrl* text_ctrl_25;
    wxStaticText* label_32;
    wxChoice* choice_6;
    wxCheckBox* checkbox_1;
    wxStaticText* label_33;
    wxChoice* choice_7;
    wxStaticText* label_34;
    wxTextCtrl* text_ctrl_26;
    wxStaticText* label_35;
    wxChoice* choice_8;
    wxStaticText* label_36;
    wxChoice* choice_9;
    wxStaticText* label_37;
    wxChoice* choice_10;
    wxStaticText* label_38;
    wxChoice* choice_11;
    wxStaticText* label_39;
    wxChoice* choice_12;
    wxStaticText* label_40;
    wxChoice* choice_13;
    wxStaticText* label_41;
    wxChoice* choice_14;
    wxStaticText* label_42;
    wxChoice* choice_15;
    wxStaticText* label_43;
    wxTextCtrl* text_ctrl_27;
    wxStaticText* label_1;
    wxChoice* choice_16;
    wxStaticText* label_44;
    wxChoice* choice_17;
    wxStaticText* label_45;
    wxChoice* choice_18;
    wxButton* button_1;
    wxPanel* notebook_2_pane_1;
    wxCheckBox* checkbox_44;
    wxCheckBox* checkbox_64;
    wxCheckBox* checkbox_45;
    wxCheckBox* checkbox_65;
    wxCheckBox* checkbox_46;
    wxCheckBox* checkbox_66;
    wxCheckBox* checkbox_47;
    wxCheckBox* checkbox_67;
    wxCheckBox* checkbox_48;
    wxCheckBox* checkbox_68;
    wxCheckBox* checkbox_49;
    wxCheckBox* checkbox_69;
    wxCheckBox* checkbox_50;
    wxCheckBox* checkbox_70;
    wxCheckBox* checkbox_51;
    wxCheckBox* checkbox_71;
    wxCheckBox* checkbox_52;
    wxCheckBox* checkbox_72;
    wxCheckBox* checkbox_53;
    wxCheckBox* checkbox_73;
    wxCheckBox* checkbox_54;
    wxCheckBox* checkbox_74;
    wxCheckBox* checkbox_55;
    wxCheckBox* checkbox_75;
    wxCheckBox* checkbox_56;
    wxCheckBox* checkbox_76;
    wxCheckBox* checkbox_57;
    wxCheckBox* checkbox_77;
    wxCheckBox* checkbox_58;
    wxCheckBox* checkbox_78;
    wxCheckBox* checkbox_59;
    wxCheckBox* checkbox_79;
    wxCheckBox* checkbox_60;
    wxCheckBox* checkbox_80;
    wxCheckBox* checkbox_61;
    wxCheckBox* checkbox_81;
    wxCheckBox* checkbox_62;
    wxCheckBox* checkbox_82;
    wxCheckBox* checkbox_63;
    wxCheckBox* checkbox_83;
    wxCheckBox* checkbox_84;
    wxCheckBox* checkbox_88;
    wxCheckBox* checkbox_85;
    wxCheckBox* checkbox_89;
    wxCheckBox* checkbox_86;
    wxCheckBox* checkbox_90;
    wxCheckBox* checkbox_87;
    wxCheckBox* checkbox_91;
    wxCheckBox* checkbox_92;
    wxCheckBox* checkbox_92_copy_15;
    wxCheckBox* checkbox_92_copy;
    wxCheckBox* checkbox_92_copy_15_copy;
    wxCheckBox* checkbox_92_copy_1;
    wxCheckBox* checkbox_92_copy_15_copy_1;
    wxCheckBox* checkbox_92_copy_2;
    wxCheckBox* checkbox_92_copy_15_copy_2;
    wxCheckBox* checkbox_92_copy_3;
    wxCheckBox* checkbox_92_copy_15_copy_3;
    wxCheckBox* checkbox_92_copy_4;
    wxCheckBox* checkbox_92_copy_15_copy_4;
    wxCheckBox* checkbox_92_copy_5;
    wxCheckBox* checkbox_92_copy_15_copy_5;
    wxCheckBox* checkbox_92_copy_6;
    wxCheckBox* checkbox_92_copy_15_copy_6;
    wxCheckBox* checkbox_92_copy_7;
    wxCheckBox* checkbox_92_copy_15_copy_7;
    wxCheckBox* checkbox_92_copy_8;
    wxCheckBox* checkbox_92_copy_15_copy_8;
    wxCheckBox* checkbox_92_copy_9;
    wxCheckBox* checkbox_92_copy_15_copy_9;
    wxCheckBox* checkbox_92_copy_10;
    wxCheckBox* checkbox_92_copy_15_copy_10;
    wxCheckBox* checkbox_92_copy_11;
    wxCheckBox* checkbox_92_copy_15_copy_11;
    wxCheckBox* checkbox_92_copy_12;
    wxCheckBox* checkbox_92_copy_15_copy_12;
    wxCheckBox* checkbox_92_copy_13;
    wxCheckBox* checkbox_92_copy_15_copy_13;
    wxCheckBox* checkbox_92_copy_14;
    wxCheckBox* checkbox_92_copy_15_copy_14;
    wxButton* button_2;
    wxButton* button_3;
    wxButton* button_4;
    wxPanel* panel_1;
    wxPanel* notebook_2_pane_3;
    wxNotebook* notebook_2;
    wxPanel* notebook_1_pane_1;
    wxPanel* notebook_1_pane_2;
    wxPanel* notebook_1_pane_3;
    wxPanel* notebook_1_pane_4;
    wxPanel* notebook_1_pane_5;
    wxNotebook* notebook_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnNew(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSave(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSaveAs(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnQuit(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnMonsterListSel(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnVitality(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PHYSICSEDITORMAINFRAME_H
