// -*- C++ -*- generated by wxGlade 0.5 on Mon Aug 13 13:06:37 2007 from C:\0save\marathon\EditorOnes\PhysicsEditorOneWX\src\res\PhysicsEditorOneWX.wxg

#include "PhysicsEditorMainFrame.h"


PhysicsEditorMainFrame::PhysicsEditorMainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos, const wxSize& size, long style):
    wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE)
{
    // begin wxGlade: PhysicsEditorMainFrame::PhysicsEditorMainFrame
    notebook_1 = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_LEFT);
    frame_1_menubar = new wxMenuBar();
    SetMenuBar(frame_1_menubar);
    wxMenu* File = new wxMenu();
    File->Append(wxID_NEW, wxT("&New"), wxT("Create new physics"), wxITEM_NORMAL);
    File->Append(wxID_OPEN, wxT("&Open"), wxEmptyString, wxITEM_NORMAL);
    File->Append(wxID_SAVE, wxT("&Save"), wxT("Save current physics"), wxITEM_NORMAL);
    File->Append(wxID_SAVEAS, wxT("Save As..."), wxT("Save current physics as other file"), wxITEM_NORMAL);
    File->AppendSeparator();
    File->Append(wxID_QUIT, wxT("&Quit"), wxT("Quit application"), wxITEM_NORMAL);
    frame_1_menubar->Append(File, wxT("&File"));
    notebook_1_pane_1 = new wxPanel(notebook_1, wxID_ANY);
    notebook_1_pane_2 = new wxPanel(notebook_1, wxID_ANY);
    notebook_1_pane_3 = new wxPanel(notebook_1, wxID_ANY);
    notebook_1_pane_4 = new wxPanel(notebook_1, wxID_ANY);
    notebook_1_pane_5 = new wxPanel(notebook_1, wxID_ANY);

    set_properties();
    do_layout();
    // end wxGlade
}


BEGIN_EVENT_TABLE(PhysicsEditorMainFrame, wxFrame)
    // begin wxGlade: PhysicsEditorMainFrame::event_table
    EVT_MENU(wxID_NEW, PhysicsEditorMainFrame::OnNew)
    EVT_MENU(wxID_SAVE, PhysicsEditorMainFrame::OnSave)
    EVT_MENU(wxID_SAVEAS, PhysicsEditorMainFrame::OnSaveAs)
    EVT_MENU(wxID_QUIT, PhysicsEditorMainFrame::OnQuit)
    // end wxGlade
END_EVENT_TABLE();


void PhysicsEditorMainFrame::OnNew(wxCommandEvent &event)
{
    event.Skip();
    std::cout<<"Event handler (PhysicsEditorMainFrame::OnNew) not implemented yet"<<std::endl; //notify the user that he hasn't implemented the event handler yet
}


void PhysicsEditorMainFrame::OnSave(wxCommandEvent &event)
{
    event.Skip();
    std::cout<<"Event handler (PhysicsEditorMainFrame::OnSave) not implemented yet"<<std::endl; //notify the user that he hasn't implemented the event handler yet
}


void PhysicsEditorMainFrame::OnSaveAs(wxCommandEvent &event)
{
    event.Skip();
    std::cout<<"Event handler (PhysicsEditorMainFrame::OnSaveAs) not implemented yet"<<std::endl; //notify the user that he hasn't implemented the event handler yet
}


void PhysicsEditorMainFrame::OnQuit(wxCommandEvent &event)
{
    event.Skip();
    std::cout<<"Event handler (PhysicsEditorMainFrame::OnQuit) not implemented yet"<<std::endl; //notify the user that he hasn't implemented the event handler yet
}


// wxGlade: add PhysicsEditorMainFrame event handlers


void PhysicsEditorMainFrame::set_properties()
{
    // begin wxGlade: PhysicsEditorMainFrame::set_properties
    SetTitle(wxT("frame_1"));
    // end wxGlade
}


void PhysicsEditorMainFrame::do_layout()
{
    // begin wxGlade: PhysicsEditorMainFrame::do_layout
    wxBoxSizer* sizer_1 = new wxBoxSizer(wxVERTICAL);
    notebook_1->AddPage(notebook_1_pane_1, wxT("Monsters"));
    notebook_1->AddPage(notebook_1_pane_2, wxT("Effects"));
    notebook_1->AddPage(notebook_1_pane_3, wxT("Projectiles"));
    notebook_1->AddPage(notebook_1_pane_4, wxT("Physics"));
    notebook_1->AddPage(notebook_1_pane_5, wxT("Weapons"));
    sizer_1->Add(notebook_1, 1, wxEXPAND, 0);
    SetSizer(sizer_1);
    sizer_1->Fit(this);
    Layout();
    // end wxGlade
}

