// -*- C++ -*- generated by wxGlade 0.5 on Mon Aug 13 13:06:37 2007 from C:\0save\marathon\EditorOnes\PhysicsEditorOneWX\src\res\PhysicsEditorOneWX.wxg

#include <wx/wx.h>
#include <wx/image.h>

#ifndef PHYSICSEDITORMAINFRAME_H
#define PHYSICSEDITORMAINFRAME_H

// begin wxGlade: ::dependencies
#include <wx/notebook.h>
// end wxGlade


class PhysicsEditorMainFrame: public wxFrame {
public:
    // begin wxGlade: PhysicsEditorMainFrame::ids
    // end wxGlade

    PhysicsEditorMainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos=wxDefaultPosition, const wxSize& size=wxDefaultSize, long style=wxDEFAULT_FRAME_STYLE);

private:
    // begin wxGlade: PhysicsEditorMainFrame::methods
    void set_properties();
    void do_layout();
    // end wxGlade

protected:
    // begin wxGlade: PhysicsEditorMainFrame::attributes
    wxMenuBar* frame_1_menubar;
    wxPanel* notebook_1_pane_1;
    wxPanel* notebook_1_pane_2;
    wxPanel* notebook_1_pane_3;
    wxPanel* notebook_1_pane_4;
    wxPanel* notebook_1_pane_5;
    wxNotebook* notebook_1;
    // end wxGlade

    DECLARE_EVENT_TABLE();

public:
    void OnNew(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSave(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnSaveAs(wxCommandEvent &event); // wxGlade: <event_handler>
    void OnQuit(wxCommandEvent &event); // wxGlade: <event_handler>
}; // wxGlade: end class


#endif // PHYSICSEDITORMAINFRAME_H
